--- 
#inception

version: '3.0'

networks: 
    inception_server:

volumes:
  database:
    driver_opts:
      o: bind
      type: volume
      device: /home/samin/data/database

  wp:
    driver_opts:
      o: bind
      type: volume
      device: /home/samin/data/wordpress


services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports: 
      - "443:443"
    networks:
      - inception_server
    volumes:
      - wp:/var/www/wordpress
    env_file:
      - .env
    restart: always

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - inception_server
    volumes:
      - database:/var/www/database
    env_file:
      - .env
    restart: always

  wordpress: 
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    ports:
      - "9000:9000"
    networks:
      - inception_server
    volumes:
      - wp:/var/www/wordpress
    env_file:
      - .env
    restart: always


    
...